---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fief-pv-pg
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pg"

