apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fief

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: secret-pg
    envs:
      - ./env/pg.env
  - name: secret-fief
    envs:
      - ./env/fief.env
